version: '3.7'
services:
    db:
        image: "mariadb:${MARIADB_VERSION}"
        container_name: "${APP_NAME}_db"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - "${MARIADB_PORT}:3306"
    web:
        build:
            context: .
            args:
                MAGENTO_ZIP_FILE: "${MAGENTO_ZIP_FILE}"
        container_name: "${APP_NAME}_web"
        depends_on:
            - db
        ports:
            - "${APP_PORT}:80"
        volumes:
            - "${MAGENTO_APP_DIR}:/var/www/html/app:delegated"
            - "${MAGENTO_LOG_DIR}:/var/www/html/var/log:delegated"
            - "./composer.json:/var/www/html/composer.json:delegated"
            - "./composer.lock:/var/www/html/composer.lock:delegated"