version: '3.7'
services:
    db:
        image: "mariadb:${MARIADB_VERSION}"
        container_name: "${APP_NAME}_db"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        ports:
            - "${MARIADB_PORT}:3306"
    web:
        build:
            context: .
            args:
                VHOST_FILE: "vhosts.conf"
        container_name: "${APP_NAME}_web"
        depends_on:
            - db
        ports:
            - "${APP_PORT}:80"
        volumes:
            - "${MAGENTO_DIR}/app:/var/www/html/app:delegated"
            - "${MAGENTO_DIR}/var/log:/var/www/html/var/log:delegated"